### ISSUE TITLE
Brackets and Pagination

### ISSUE THREAD

**Issue by Dgvalerio** [sauce-consultants/ember-mirage-sauce#2]
Hello, I found the ember-mirage-sauce very interesting, but I would like to know if you have any plans to support also "_%5b_" and "_%5d_" in addition to brackets.
I would also like to ask if you plan to include _limit/offset_ support in pagination, in addition to the already existent _number/page._
Best Regards!

**Comment by glauberferreira** [comment]
+1

**Comment by th3hamburgler** [comment]
Thanks @Dgvalerio, I'd assumed  %5b & %5d was already handled as all ember data requests get urlencoded?

Pagination limit and offset are also supported with page[number] & page[size]

`api/v1/things?page%5Bnumber%5D=2&page%5Bsize%5D=50`
