### ISSUE TITLE
Search functionality broken due to `[].pushObject()` call

### ISSUE THREAD

**Issue by nickschot** [sauce-consultants/ember-mirage-sauce#3]
https://github.com/sauce-consultants/ember-mirage-sauce/blob/09d95aab8b0ee9ee3e9dbda38d5164c9aba16a5a/addon/mirage-serializers/json-api-serializer.js#L320-L343

In the above on line 335 `pushObject` seems to be called on a native array, which isn't possible. Results in at least broken search functionality.

**Comment by th3hamburgler** [comment]
Apologies for the huge delay here! This bug was closed a while a go

**Comment by nickschot** [comment]
Thanks! Means I can get rid of my fork repo 🙌
