### ISSUE TITLE
How to add sorting?

### ISSUE THREAD

**Issue by rizkysyazuli** [sauce-consultants/ember-mirage-sauce#6]
The docs is a bit unclear, how do i add a `sort` param to my request exactly? This doesn't work

```js
this.store.findAll('post', { include: 'user', sort: 'date' })
```

**Comment by th3hamburgler** [comment]
Apologies, this is probably to late now

As long as your `post` model has an attribute named _date_ and that can be ordered like a string this should work. 

I've bumped this addon to 0.1.0 with the addition added debug flag to help diagnose issues like this.
